name: docs

on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependences
        run: |
          python -m pip install --upgrade pip
          cd ./docs
          pip install -r requirements.txt
      - name: Build
        run: |
          ./build_docs.sh html
          cp .gitignore ./docs/build/html/
      - name: Prepare tag
        id: prepare_tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG_NAME="${GITHUB_REF##refs/tags/}"
          echo "::set-output name=tag_name::${TAG_NAME}"
          echo "::set-output name=deploy_tag_name::${TAG_NAME}-docs"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
          tag_name: ${{ steps.prepare_tag.outputs.deploy_tag_name }}
          tag_message: "${{ steps.prepare_tag.outputs.tag_name }} docs"
