name: tests

on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"
  # pull_request:
  #   branches: [ main ]

jobs:
  testing:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependences
        run: |
          python -m pip install --upgrade pip
          cd ./docs
          pip install -r requirements.txt
          cd ../tests
          pip install -r requirements.txt
      - name: Run tests
        run: ./run_tests.sh
