name: tests

on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"
  # pull_request:
  #   branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependences
        run: |
          python -m pip install --upgrade pip
          cd ./docs
          pip install -r requirements.txt
      - name: Run unittests
        run: python -m unittest discover
      - name: Run doctests
        run: |
          cd ./docs
          make doctest
